events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/publication/ {
            proxy_pass http://publication-api:80/api/publication/;
        }

        location /api/search/ {
            proxy_pass http://discovery-api:80/api/search/;
        }

;         location /api/subscription/ {
;             proxy_pass http://subscription-api:80/api/subscription/;
;         }
    }
}