services:
  postgres:
    image: postgres:15
    container_name: integration-platform-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: integration_platform
      POSTGRES_MULTIPLE_DATABASES: publication_db,subscription_db
    ports:
      - "5480:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh

  publication-api:
    build:
      context: .
      dockerfile: IntegrationPlatform.Publication.API/Dockerfile
    container_name: publication-api
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PublicationDbContext=Host=postgres;Port=5432;Database=integration_platform;Username=admin;Password=password;Search Path=publication
    depends_on:
      - postgres
    ports:
      - "5001:8080"
  
  search-api:
    build:
      context: .
      dockerfile: IntegrationPlatform.Search.API/Dockerfile
    container_name: search-api
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DiscoveryDbContext=Host=postgres;Port=5432;Database=integration_platform;Username=admin;Password=password;Search Path=publication
    depends_on:
      - postgres
    ports:
      - "5002:8080"

  subscription-api:
    build:
      context: .
      dockerfile: IntegrationPlatform.Subscription.API/Dockerfile
    container_name: subscription-api
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__SubscriptionDbContext=Host=postgres;Port=5432;Database=integration_platform;Username=admin;Password=password;Search Path=subscription
    depends_on:
      - postgres
    ports:
      - "5003:8080"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: integration-frontend
    ports:
      - "8080:80"
    depends_on:
      - publication-api
      - search-api
      - subscription-api

volumes:
  postgres_data: