<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-IntegrationPlatform.TestProducer-2f2709d0-ef2c-4b68-9181-897440961f1b</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Confluent.Kafka" Version="2.13.2" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0"/>
    </ItemGroup>
</Project>
