// <auto-generated />
using System;
using IntegrationPlatform.Subscription.DataAccess.DatabaseConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntegrationPlatform.Subscription.DataAccess.DatabaseConnection.Migrations
{
    [DbContext(typeof(SubscriptionDbContext))]
    [Migration("20251002144641_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("subscription")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntegrationPlatform.Common.Models.DataInterface", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("InterfaceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("DataInterfaces", "subscription");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("IntegrationPlatform.Common.Models.OrchestrationConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ExecutionTimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(300);

                    b.Property<string>("IntegrationPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InterfacePublicationId")
                        .HasColumnType("integer");

                    b.Property<int>("InterfaceSubscriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRetryAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("RetryDelaySeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<string>("ScheduleCron")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("*/5 * * * *");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("InterfaceSubscriptionId")
                        .IsUnique();

                    b.ToTable("OrchestrationConfig", "subscription");
                });

            modelBuilder.Entity("IntegrationPlatform.Common.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products", "subscription");
                });

            modelBuilder.Entity("IntegrationPlatform.Common.Models.ApiInterface", b =>
                {
                    b.HasBaseType("IntegrationPlatform.Common.Models.DataInterface");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ToTable("ApiInterface", "subscription");
                });

            modelBuilder.Entity("IntegrationPlatform.Common.Models.DatabaseInterface", b =>
                {
                    b.HasBaseType("IntegrationPlatform.Common.Models.DataInterface");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.ToTable("DatabaseInterface", "subscription");
                });

            modelBuilder.Entity("IntegrationPlatform.Common.Models.KafkaInterface", b =>
                {
                    b.HasBaseType("IntegrationPlatform.Common.Models.DataInterface");

                    b.Property<string>("BootstrapServers")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ToTable("KafkaInterface", "subscription");
                });

            modelBuilder.Entity("IntegrationPlatform.Common.Models.DataInterface", b =>
                {
                    b.HasOne("IntegrationPlatform.Common.Models.Product", "Product")
                        .WithMany("Interfaces")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IntegrationPlatform.Common.Models.OrchestrationConfig", b =>
                {
                    b.HasOne("IntegrationPlatform.Common.Models.DataInterface", "DataInterface")
                        .WithOne("OrchestrationConfig")
                        .HasForeignKey("IntegrationPlatform.Common.Models.OrchestrationConfig", "InterfaceSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataInterface");
                });

            modelBuilder.Entity("IntegrationPlatform.Common.Models.ApiInterface", b =>
                {
                    b.HasOne("IntegrationPlatform.Common.Models.DataInterface", null)
                        .WithOne()
                        .HasForeignKey("IntegrationPlatform.Common.Models.ApiInterface", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationPlatform.Common.Models.DatabaseInterface", b =>
                {
                    b.HasOne("IntegrationPlatform.Common.Models.DataInterface", null)
                        .WithOne()
                        .HasForeignKey("IntegrationPlatform.Common.Models.DatabaseInterface", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationPlatform.Common.Models.KafkaInterface", b =>
                {
                    b.HasOne("IntegrationPlatform.Common.Models.DataInterface", null)
                        .WithOne()
                        .HasForeignKey("IntegrationPlatform.Common.Models.KafkaInterface", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationPlatform.Common.Models.DataInterface", b =>
                {
                    b.Navigation("OrchestrationConfig")
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationPlatform.Common.Models.Product", b =>
                {
                    b.Navigation("Interfaces");
                });
#pragma warning restore 612, 618
        }
    }
}
